/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const GetScoreIndexLazyImport = createFileRoute('/get-score/')()
const BenefitsIndexLazyImport = createFileRoute('/benefits/')()
const AboutUsIndexLazyImport = createFileRoute('/about-us/')()
const ScoreScoreIdLazyImport = createFileRoute('/score/$scoreId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GetScoreIndexLazyRoute = GetScoreIndexLazyImport.update({
  path: '/get-score/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/get-score/index.lazy').then((d) => d.Route),
)

const BenefitsIndexLazyRoute = BenefitsIndexLazyImport.update({
  path: '/benefits/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/benefits/index.lazy').then((d) => d.Route),
)

const AboutUsIndexLazyRoute = AboutUsIndexLazyImport.update({
  path: '/about-us/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/about-us/index.lazy').then((d) => d.Route),
)

const ScoreScoreIdLazyRoute = ScoreScoreIdLazyImport.update({
  path: '/score/$scoreId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/score/$scoreId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/score/$scoreId': {
      id: '/score/$scoreId'
      path: '/score/$scoreId'
      fullPath: '/score/$scoreId'
      preLoaderRoute: typeof ScoreScoreIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/benefits/': {
      id: '/benefits/'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/get-score/': {
      id: '/get-score/'
      path: '/get-score'
      fullPath: '/get-score'
      preLoaderRoute: typeof GetScoreIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ScoreScoreIdLazyRoute,
  AboutUsIndexLazyRoute,
  BenefitsIndexLazyRoute,
  GetScoreIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/score/$scoreId",
        "/about-us/",
        "/benefits/",
        "/get-score/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/score/$scoreId": {
      "filePath": "score/$scoreId.lazy.tsx"
    },
    "/about-us/": {
      "filePath": "about-us/index.lazy.tsx"
    },
    "/benefits/": {
      "filePath": "benefits/index.lazy.tsx"
    },
    "/get-score/": {
      "filePath": "get-score/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
